version: '3.8'

services:
  responder:
    image: registry.gitlab.com/batteryenergyback/applications/recruitment/responder:latest
    container_name: responder
    restart: always
    pull_policy: always
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"